Feature/add label endpoint
saddboys/Collaborative_content_coding pull request #11
Opened 2020-09-01 01:32 UTC by RajanGuptaNZ

#### Description
Added an addLabel endpoint to the backend.
Body of request is:
```
{
    "projectID": x,
    "documentID": x
    "userID": x,
    "label": "xxx"
}
```

Responds with:
```
{
    "message": "Added label successfully",
    "status_code": 200
} 
``` 
or 
```
{
    "message": "Missing xxx",
    "status_code": 400
}
```

#### Review Checklist
- [x] The requirements on the description have been met
- [x] The relevant documentation has been updated:
    - [x] code comments for classes / methods / complex statements
- [x] Tests:
    - [x] Tested using Postman
- [ ] Tested by reviewer

2020-09-01 03:36 UTC, tnzhu requested changes

2020-09-01 03:36 UTC, tnzhu commented on backend/main.py
> +        projectID = int(request.json['projectID'])
The current ID's are automatically generated when documents are added into the collections, so we'll need to discuss if we're using those, or setting our own ID's.

Documents are the exception at the moment, the id field is "identifier"

We could also use the User's email as their ID

2020-09-01 03:36 UTC, tnzhu commented on backend/main.py
> +    ### Add to DB ###
See `add_user_and_label` in backend/model/document.py

2020-09-04 02:01 UTC, saddboys commented on backend/main.py
> +    ### Add to DB ###
Yeah we will likely use the mongoDB IDs for this purpose

2020-09-04 02:02 UTC, saddboys commented on backend/main.py
> +        projectID = int(request.json['projectID'])
Yeah we will likely use the mongodb IDs

2020-09-04 03:03 UTC, RajanGuptaNZ commented on backend/main.py
> +        projectID = int(request.json['projectID'])
Does this really affect what the endpoint keys are called?

2020-09-04 03:05 UTC, RajanGuptaNZ commented on backend/main.py
> +    ### Add to DB ###
I've kind of mocked this up in my new commits, but I can't fully implement it until I can get users & documents from the db

2020-09-19 02:06 UTC, saddboys approved these changes
looks fine

2020-09-19 02:06 UTC, merged