projects load up on creation without refreshing
saddboys/Collaborative_content_coding pull request #119
Opened 2020-10-06 12:13 UTC by Akrya

#### Description

#### Review Checklist
- [ ] The requirements on the description have been met
- [ ] The relevant documentation has been updated:
    - [ ] code comments for classes / methods / complex statements
    - [ ] package readme
    - [ ] documentation for high level approaches or product info
- [ ] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

2020-10-07 07:30 UTC, saddboys requested changes
This does not work? Try looking at it again please

2020-10-10 00:34 UTC, tnzhu commented
![image](https://user-images.githubusercontent.com/37363804/95641156-29d8a680-0afd-11eb-86fc-d5bc240d63b9.png)

This happens when I try to create a project with an invalid name. It doesn't appear to affect the functionality of anything but could be misleading to the user. 

When I created a valid new project in this state it proceeded as normal

2020-10-12 06:40 UTC, mliu433 approved these changes

2020-10-12 21:50 UTC, saddboys approved these changes

2020-10-12 21:51 UTC, merged