Feature/frontend file upload UI
saddboys/Collaborative_content_coding pull request #14
Opened 2020-09-02 19:44 UTC by Akrya

#### Description

#### Review Checklist
- [x] The requirements on the description have been met
- [x] The relevant documentation has been updated:
    - [x] code comments for classes / methods / complex statements
    - [x] package readme
    - [x] documentation for high level approaches or product info
- [ ] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

No interaction with backend yet

2020-09-02 23:34 UTC, Cvos0162 requested changes

2020-09-02 23:34 UTC, Cvos0162 commented on app/src/pages/MainPage.tsx
> +  interface Document {
Not needed

2020-09-02 23:34 UTC, Cvos0162 commented on app/src/pages/MainPage.tsx
> +  const ProjectPage: React.FC = () => {
rename please. we got duplicate. gotta match to the filename

2020-09-02 23:34 UTC, Cvos0162 commented on app/src/pages/MainPage.tsx
> +  export default ProjectPage;
Same here

2020-09-02 23:34 UTC, Cvos0162 commented on app/src/App.tsx
> +            <Route path="/mainpage" component={MainPage} exact />
maybe consider having root / as the main page?

2020-09-02 23:34 UTC, Cvos0162 commented on app/src/App.tsx
> +            <Route path="/mainpage" component={MainPage} exact />
Just an idea

2020-09-03 02:25 UTC, tnzhu commented
Hey, overall the page looks great, but my understanding was that this page should allow users to select a file to upload. I don't see this functionality implemented here?

2020-09-03 02:31 UTC, Akrya commented
> Hey, overall the page looks great, but my understanding was that this page should allow users to select a file to upload. I don't see this functionality implemented here?
I assumed the main page was for creating a project, and you can upload files inside the "project page".  There is no actual functionality yet but the UI has been set up if you go on the path  "/project/:name".

2020-09-03 02:33 UTC, tnzhu commented
> > Hey, overall the page looks great, but my understanding was that this page should allow users to select a file to upload. I don't see this functionality implemented here?
> 
> I assumed the main page was for creating a project, and you can upload files inside the "project page". There is no actual functionality yet but the UI has been set up if you go on the path "/project/:name".

Ah, sweet, I didn't see that we had individual project pages. Looking good!

2020-09-03 13:49 UTC, Cvos0162 approved these changes
LGTM!

2020-09-03 23:38 UTC, merged