Connect export frontend to backend
saddboys/Collaborative_content_coding pull request #34
Opened 2020-09-22 11:02 UTC by jwar663

#### Description
Connect export frontend to backend

#### Review Checklist
- [x] The requirements on the description have been met
- [x] The relevant documentation has been updated:
    - [x] code comments for classes / methods / complex statements
    - [x] package readme
    - [x] documentation for high level approaches or product info
- [x] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

2020-09-22 20:58 UTC, mliu433 submitted a review, later dismissed
need response status handler, see ProjectServices.ts

2020-09-24 00:20 UTC, tnzhu requested changes

2020-09-24 00:20 UTC, tnzhu commented on app/src/services/ProjectServices.ts
> +        .then(handleResponse)
I think we might need to write a custom response handler since the backend sends a file?

2020-09-27 00:16 UTC, tnzhu approved these changes
Good work, LGTM!

2020-09-27 00:17 UTC, tnzhu approved these changes

2020-09-27 00:17 UTC, tnzhu approved these changes

2020-09-27 01:59 UTC, saddboys approved these changes

2020-09-27 02:00 UTC, merged