Feature/user labels per document
saddboys/Collaborative_content_coding pull request #48
Opened 2020-09-23 06:29 UTC by RajanGuptaNZ

#### Description
Added page to view user assigned labels for each document.
/project/:project/document/:document_id
ie: /project/New_Project/Document/5f6709e7e1991df825dafa96

#### Review Checklist
- [ ] The requirements on the description have been met
- [ ] The relevant documentation has been updated:
    - [ ] code comments for classes / methods / complex statements
    - [ ] package readme
    - [ ] documentation for high level approaches or product info
- [ ] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

2020-09-23 22:31 UTC, Cvos0162 requested changes
merge and clean up. Otherwise looks good to me 👍

2020-09-23 22:31 UTC, Cvos0162 commented on app/src/pages/DocumentPage.tsx
> +        projectServices.getDocument(project, document_id, firebase)
when merging, use DocumentServices.
Let's match the structure to the backend API yeah?

2020-09-23 22:31 UTC, Cvos0162 commented on app/src/pages/DocumentPage.tsx
> +            console.log(data)
please remove all the console.log()

2020-09-23 22:31 UTC, Cvos0162 commented on app/src/pages/DocumentPage.tsx
> +                xxx
What is this button for?

2020-09-23 22:31 UTC, Cvos0162 commented on app/src/services/ProjectServices.ts
> + function getDocument(project_name: any, document_id: any, firebase: any) {
refer DocumentService

2020-09-23 22:31 UTC, Cvos0162 commented on app/src/pages/DocumentPage.tsx
> +const users_and_labels_init: Users_and_Labels[] = [
I dont think you need this
if you are concerned about type casting for useState
you can do useState<Users_and_Labels[]>([]) instread

2020-09-24 04:46 UTC, RajanGuptaNZ commented
Made the requested changes

2020-09-24 05:06 UTC, Cvos0162 approved these changes
LGTM 👍

2020-09-24 05:06 UTC, merged