Feature/labelling documents
saddboys/Collaborative_content_coding pull request #52
Opened 2020-09-23 10:51 UTC by Cvos0162

#### Description
In Project page, we can now assign labels into documents

#### Review Checklist
- [ ] The requirements on the description have been met
- [ ] The relevant documentation has been updated:
    - [ ] code comments for classes / methods / complex statements
    - [ ] package readme
    - [ ] documentation for high level approaches or product info
- [ ] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

2020-09-23 22:32 UTC, saddboys requested changes
Works, but there is a slight delay between assigning a tag and the tag appearing on the UI. Can this be fixed first?

2020-09-24 00:53 UTC, Cvos0162 commented
> Works, but there is a slight delay between assigning a tag and the tag appearing on the UI. Can this be fixed first?

Changed!

2020-09-24 05:27 UTC, tnzhu approved these changes
LGTM! Just need to address the file conflict now :)

2020-09-24 05:28 UTC, tnzhu approved these changes

2020-09-24 05:30 UTC, saddboys approved these changes

2020-09-24 05:31 UTC, merged