create project Integration added
saddboys/Collaborative_content_coding pull request #55
Opened 2020-09-23 19:25 UTC by Akrya

#### Description

#### Review Checklist
- [X] The requirements on the description have been met
- [X] The relevant documentation has been updated:
    - [X] code comments for classes / methods / complex statements
    - [X] package readme
    - [X] documentation for high level approaches or product info
- [ ] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

2020-09-24 03:30 UTC, Cvos0162 requested changes
I hope it isn't too much to handle. I guess grab someone if need help ;)

2020-09-24 03:30 UTC, Cvos0162 commented on app/src/pages/MainPage.tsx
> +<<<<<<< HEAD
I still see a merge error, can you check this again?

2020-09-24 03:30 UTC, Cvos0162 commented on app/src/pages/ProjectPage.tsx
> +      <Header routerLink={"/"} name={"User"}/>
This will be changed in next merge

2020-09-24 03:30 UTC, Cvos0162 commented on app/src/services/ProjectServices.ts
> + async function getProjectTags(project: string, firebase:any) {
master has this function in services/labelServices

2020-09-24 03:30 UTC, Cvos0162 commented on app/src/services/ProjectServices.ts
> + async function setProjectTags(project: string, label_name: string, firebase:any) {
maybe move this over to services/labelServices too

2020-09-24 13:19 UTC, Akrya commented
> I hope it isn't too much to handle. I guess grab someone if need help ;)

ok I think i got it. Ill fix it tomorrow morning if its still bad sorry

2020-09-29 06:03 UTC, Cvos0162 approved these changes
All working

2020-09-29 06:05 UTC, merged