Feature/add user by email
saddboys/Collaborative_content_coding pull request #63
Opened 2020-09-28 00:36 UTC by xoneon

#### Description
Can add users by email using a text input.
Prevents when: input is empty, user does not exist, or user is already added

#### Review Checklist
- [ ] The requirements on the description have been met
- [ ] The relevant documentation has been updated:
    - [ ] code comments for classes / methods / complex statements
    - [ ] package readme
    - [ ] documentation for high level approaches or product info
- [ ] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

2020-09-29 06:30 UTC, Cvos0162 commented on app/src/components/SettingsUsers.tsx
> +      userService.getAllUsers()
This getAllUsers() is old, because the new backend API needs page and page_size as the query input

2020-09-29 06:55 UTC, Cvos0162 requested changes

2020-09-29 06:55 UTC, Cvos0162 commented on app/src/components/SettingsUsers.tsx
> +      userService.getAllUsers()
the service getAllUsers() is old and now requires a page and page_size for backend API as a query.
And this causes a problem when trying to check if the given email exists in the database since you can't fetch all the users at once now. It's likely that there will be a lot of users in the future and getting too much data isn't good. 

So I think we need to set up the backend API that checks through the users with the given email and add by the email. If there is no user with given email, it should return an error, so then we can catch that error to say on the modal

2020-09-29 07:31 UTC, tnzhu commented on app/src/components/SettingsUsers.tsx
> +      userService.getAllUsers()
I agree, we can make an API that requires the email to be sent in the request body and behaves as In Ha has described above.

We would also need to make a new service for this API.

2020-09-29 09:31 UTC, tnzhu commented on app/src/components/SettingsUsers.tsx
> +      userService.getAllUsers()
PR for API and service can be found here: https://github.com/saddboys/Collaborative_content_coding/pull/74

2020-09-30 00:19 UTC, xoneon commented on app/src/components/SettingsUsers.tsx
> +      userService.getAllUsers()
updated to not call getAllUsers()

2020-09-30 05:25 UTC, mliu433 approved these changes

2020-09-30 05:33 UTC, Cvos0162 approved these changes

2020-09-30 06:11 UTC, merged